package interfaces;

public class PainelDocumentario extends javax.swing.JPanel {
    public PainelDocumentario() {
        initComponents();
    }
    
    public int getValor() {
        return Integer.parseInt(valorTextField.getText());
    }
    
    public void setValor(int valor) {
        valorTextField.setText(Integer.toString(valor));
    }
    
    public boolean getPropriedadeIntelectual() {
        return propriedadeIntelectualCheckBox.isSelected();
    }
    
    public void setPropriedadeIntelectual(boolean propriedadeIntelectual) {
        propriedadeIntelectualCheckBox.setSelected(propriedadeIntelectual);
    }
    
    public void limparCampos() {
        valorTextField.setText("");
        propriedadeIntelectualCheckBox.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        propriedadeIntelectualCheckBox = new javax.swing.JCheckBox();
        valorLabel = new javax.swing.JLabel();
        valorTextField = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        propriedadeIntelectualCheckBox.setText("Propriedade intelectual declarada");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(propriedadeIntelectualCheckBox, gridBagConstraints);

        valorLabel.setText("Valor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(valorLabel, gridBagConstraints);

        valorTextField.setMinimumSize(new java.awt.Dimension(80, 25));
        valorTextField.setPreferredSize(new java.awt.Dimension(80, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(valorTextField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox propriedadeIntelectualCheckBox;
    private javax.swing.JLabel valorLabel;
    private javax.swing.JTextField valorTextField;
    // End of variables declaration//GEN-END:variables
}
