package interfaces;

public class PainelFilme extends javax.swing.JPanel {
    public PainelFilme() {
        initComponents();
    }
    
    public int getDuracao() {
        return Integer.parseInt(duracaoTextField.getText());
    }
    
    public void setDuracao(int duracao) {
        duracaoTextField.setText(Integer.toString(duracao));
    }
    
    public String getProtagonista() {
        return protagonistaTextField.getText();
    }
    
    public void setProtagonista(String protagonista) {
        protagonistaTextField.setText(protagonista);
    }
    
    public void limparCampos() {
        duracaoTextField.setText("");
        protagonistaTextField.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        duracaoLabel = new javax.swing.JLabel();
        protagonistaLabel = new javax.swing.JLabel();
        duracaoTextField = new javax.swing.JTextField();
        protagonistaTextField = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        duracaoLabel.setText("Duração");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(duracaoLabel, gridBagConstraints);

        protagonistaLabel.setText("Protagonista");
        protagonistaLabel.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(protagonistaLabel, gridBagConstraints);

        duracaoTextField.setMinimumSize(new java.awt.Dimension(80, 25));
        duracaoTextField.setPreferredSize(new java.awt.Dimension(80, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(duracaoTextField, gridBagConstraints);

        protagonistaTextField.setMinimumSize(new java.awt.Dimension(200, 25));
        protagonistaTextField.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(protagonistaTextField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel duracaoLabel;
    private javax.swing.JTextField duracaoTextField;
    private javax.swing.JLabel protagonistaLabel;
    private javax.swing.JTextField protagonistaTextField;
    // End of variables declaration//GEN-END:variables
}
