package interfaces;

public class PainelSerie extends javax.swing.JPanel {
    public PainelSerie() {
        initComponents();
    }
    
    public int getTotalEpisodios() {
        return Integer.parseInt(totalEpisodiosTextField.getText());
    }
    
    public void setTotalEpisodios(int totalEpisodios) {
        totalEpisodiosTextField.setText(Integer.toString(totalEpisodios));
    }
    
    public int getAno() {
        return Integer.parseInt(anoTextField.getText());
    }
    
    public void setAno(int ano) {
        anoTextField.setText(Integer.toString(ano));
    }
    
    public void limparCampos() {
        totalEpisodiosTextField.setText("");
        anoTextField.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        totalEpisodiosLabel = new javax.swing.JLabel();
        anoLabel = new javax.swing.JLabel();
        totalEpisodiosTextField = new javax.swing.JTextField();
        anoTextField = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        totalEpisodiosLabel.setText("Total de episódios");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(totalEpisodiosLabel, gridBagConstraints);

        anoLabel.setText("Ano");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(anoLabel, gridBagConstraints);

        totalEpisodiosTextField.setMinimumSize(new java.awt.Dimension(80, 25));
        totalEpisodiosTextField.setPreferredSize(new java.awt.Dimension(80, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(totalEpisodiosTextField, gridBagConstraints);

        anoTextField.setMinimumSize(new java.awt.Dimension(80, 25));
        anoTextField.setPreferredSize(new java.awt.Dimension(80, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(anoTextField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anoLabel;
    private javax.swing.JTextField anoTextField;
    private javax.swing.JLabel totalEpisodiosLabel;
    private javax.swing.JTextField totalEpisodiosTextField;
    // End of variables declaration//GEN-END:variables
}
